services:
    shortener-postgres:
        container_name: shortener-postgres
        image: postgres
        environment:
            - POSTGRES_DB=${POSTGRES_DB}
            - POSTGRES_USER=${POSTGRES_USER}
            - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
        volumes:
            - shortener-postgres-data:/var/lib/postgresql/data
        ports:
            - "${POSTGRES_PORT}:5432"

volumes:
    shortener-postgres-data:
